# Generated by Django 4.1.5 on 2023-02-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_driver_vehicle_type_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', '4'), ('Coupe', '4'), ('SUV', '5'), ('Pickup', '6')], default='Sedan', max_length=256, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_vehicle_type',
            field=models.CharField(blank=True, choices=[('Sedan', '4'), ('Coupe', '4'), ('SUV', '5'), ('Pickup', '6')], max_length=10, verbose_name='special_vehicle_type'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Confirmed', 'Confirmed'), ('Open', 'Open')], default='Open', max_length=32),
        ),
    ]
