# Generated by Django 4.1.5 on 2023-02-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_driver_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('4', 'Coupe'), ('6', 'Pickup'), ('5', 'SUV'), ('4', 'Sedan')], max_length=256, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Completed', 'Completed'), ('Confirmed', 'Confirmed')], default='Open', max_length=32),
        ),
    ]
