# Generated by Django 4.1.5 on 2023-02-06 00:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_alter_driver_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.IntegerField(choices=[(4, 'Sedan'), (3, 'Coupe'), (5, 'SUV'), (6, 'Pcikup')], verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Open', 'Open')], default='Open', max_length=32),
        ),
        migrations.CreateModel(
            name='RideSharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('joined_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joinedride', to='user.ride')),
                ('user_sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_share', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
