# Generated by Django 4.1.6 on 2023-02-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_driver_vehicle_type_alter_ride_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.IntegerField(choices=[(4, 'Sedan'), (3, 'Coupe'), (5, 'SUV'), (6, 'Pickup')], verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_vehicle_type',
            field=models.IntegerField(blank=True, choices=[(4, 'Sedan'), (3, 'Coupe'), (5, 'SUV'), (6, 'Pickup')], null=True, verbose_name='special_vehicle_type'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Open', 'Open'), ('Confirmed', 'Confirmed')], default='Open', max_length=32),
        ),
    ]
